[package]
name = "rsqlite-vfs"
version = "0.2.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"
include.workspace = true
keywords = ["sqlite", "vfs"]
description = "Helping to implement SQLite VFS."
categories = ["development-tools::ffi", "wasm", "database"]

[dependencies]
thiserror = { version = "2.0.20", default-features = false }

[dev-dependencies]
libsqlite3-sys = { version = "0.38.2", features = ["bundled"] }
