[package]
name = "rsqlite-vfs"
version = "0.2.0"
repository = "https://github.com/Spxg/sqlite-wasm-rs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"
include.workspace = true
keywords = ["sqlite", "vfs"]
description = "Helping to implement SQLite VFS."
categories = ["development-tools::ffi", "wasm", "database"]

[dependencies]
thiserror = { version = "2.0.20", default-features = false }

[features]
# Makes memvfs shareable between threads through SQLite's mutex API. Needs a SQLite built with SQLITE_THREADSAFE > 0.
threadsafe = []

[dev-dependencies]
libsqlite3-sys = { version = "0.38.2", features = ["bundled"] }
